In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
faqs = """About the Program
What is the course fee for  Data Science Mentorship Program (DSMP 2023)
The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.
What is the total duration of the course?
The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)
What is the syllabus of the mentorship program?
We will be covering the following modules:
Python Fundamentals
Python libraries for Data Science
Data Analysis
SQL for Data Science
Maths for Machine Learning
ML Algorithms
Practical ML
MLOPs
Case studies
You can check the detailed syllabus here - https://learnwith.campusx.in/courses/CampusX-Data-Science-Mentorship-Program-637339afe4b0615a1bbed390
Will Deep Learning and NLP be a part of this program?
No, NLP and Deep Learning both are not a part of this program’s curriculum.
What if I miss a live session? Will I get a recording of the session?
Yes all our sessions are recorded, so even if you miss a session you can go back and watch the recording.
Where can I find the class schedule?
Checkout this google sheet to see month by month time table of the course - https://docs.google.com/spreadsheets/d/16OoTax_A6ORAeCg4emgexhqqPv3noQPYKU7RJ6ArOzk/edit?usp=sharing.
What is the time duration of all the live sessions?
Roughly, all the sessions last 2 hours.
What is the language spoken by the instructor during the sessions?
Hinglish
How will I be informed about the upcoming class?
You will get a mail from our side before every paid session once you become a paid user.
Can I do this course if I am from a non-tech background?
Yes, absolutely.
I am late, can I join the program in the middle?
Absolutely, you can join the program anytime.
If I join/pay in the middle, will I be able to see all the past lectures?
Yes, once you make the payment you will be able to see all the past content in your dashboard.
Where do I have to submit the task?
You don’t have to submit the task. We will provide you with the solutions, you have to self evaluate the task yourself.
Will we do case studies in the program?
Yes.
Where can we contact you?
You can mail us at nitish.campusx@gmail.com
Payment/Registration related questions
Where do we have to make our payments? Your YouTube channel or website?
You have to make all your monthly payments on our website. Here is the link for our website - https://learnwith.campusx.in/
Can we pay the entire amount of Rs 5600 all at once?
Unfortunately no, the program follows a monthly subscription model.
What is the validity of monthly subscription? Suppose if I pay on 15th Jan, then do I have to pay again on 1st Feb or 15th Feb
15th Feb. The validity period is 30 days from the day you make the payment. So essentially you can join anytime you don’t have to wait for a month to end.
What if I don’t like the course after making the payment. What is the refund policy?
You get a 7 days refund period from the day you have made the payment.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmail.com
Post registration queries
Till when can I view the paid videos on the website?
This one is tricky, so read carefully. You can watch the videos till your subscription is valid. Suppose you have purchased subscription on 21st Jan, you will be able to watch all the past paid sessions in the period of 21st Jan to 20th Feb. But after 21st Feb you will have to purchase the subscription again.
But once the course is over and you have paid us Rs 5600(or 7 installments of Rs 799) you will be able to watch the paid sessions till Aug 2024.
Why lifetime validity is not provided?
Because of the low course fee.
Where can I reach out in case of a doubt after the session?
You will have to fill a google form provided in your dashboard and our team will contact you for a 1 on 1 doubt clearance session
If I join the program late, can I still ask past week doubts?
Yes, just select past week doubt in the doubt clearance google form.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmai.com
Certificate and Placement Assistance related queries
What is the criteria to get the certificate?
There are 2 criterias:
You have to pay the entire fee of Rs 5600
You have to attempt all the course assessments.
I am joining late. How can I pay payment of the earlier months?
You will get a link to pay fee of earlier months in your dashboard once you pay for the current month.
I have read that Placement assistance is a part of this program. What comes under Placement assistance?
This is to clarify that Placement assistance does not mean Placement guarantee. So we dont guarantee you any jobs or for that matter even interview calls. So if you are planning to join this course just for placements, I am afraid you will be disappointed. Here is what comes under placement assistance
Portfolio Building sessions
Soft skill sessions
Sessions with industry mentors
Discussion on Job hunting strategies
"""

In [3]:
doc = """Retrieval Augmented Generation (RAG) is a technique that grants generative artificial intelligence models 
information retrieval capabilities. It modifies interactions with a large language model (LLM) so that the model 
responds to user queries with reference to a specified set of documents, using this information to augment information 
drawn from its own vast, static training data. This allows LLMs to use domain-specific and/or updated information. 
Use cases include providing chatbot access to internal company data or giving factual information only from an authoritative source.
The RAG process is made up of four key stages. First, all the data must be prepared and indexed for use by the LLM. 
Thereafter, each query consists of a retrieval, augmentation, and generation phase.
Indexing
Typically, the data to be referenced is converted into LLM embeddings, numerical representations in the form of large vectors. 
RAG can be used on unstructured (usually text), semi-structured, or structured data (for example knowledge graphs).
These embeddings are then stored in a vector database to allow for document retrieval.
Overview of RAG process, combining external documents and user input into an LLM prompt to get tailored output
Retrieval
Given a user query, a document retriever is first called to select the most relevant documents that will be used to augment the query.
This comparison can be done using a variety of methods, which depend in part on the type of indexing used.
Augmentation
The model feeds this relevant retrieved information into the LLM via prompt engineering of the user's original query.
Newer implementations (as of 2023) can also incorporate specific augmentation modules with abilities such as expanding queries into multiple domains 
and using memory and self-improvement to learn from previous retrievals.
Generation
Finally, the LLM can generate output based on both the query and the retrieved documents.Some models incorporate extra steps to improve output, 
such as the re-ranking of retrieved information, context selection, and fine-tuning.
Encoder
These methods center around the encoding of text as either dense or sparse vectors. Sparse vectors, used to encode the identity of a word, 
are typically dictionary length and contain almost all zeros. Dense vectors, used to encode meaning, are much smaller and contain far fewer zeros. 
Several enhancements can be made to the way similarities are calculated in the vector stores (databases).
Performance can be improved with faster dot products, approximate nearest neighors, or centroid searches.
Accuracy can be improved with Late Interactions.
Hybrid vectors: dense vector representations can be combined with sparse one-hot vectors in order to use the faster sparse dot products 
rather than the slower dense ones.Other[clarification needed] methods can combine sparse methods (BM25, SPLADE) with dense ones like DRAGON."""

### Tokenize doc

In [4]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [5]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts([doc])

In [6]:
tokenizer.word_index

{'the': 1,
 'to': 2,
 'of': 3,
 'and': 4,
 'a': 5,
 'be': 6,
 'can': 7,
 'information': 8,
 'with': 9,
 'llm': 10,
 'vectors': 11,
 'retrieval': 12,
 'data': 13,
 'or': 14,
 'query': 15,
 'in': 16,
 'used': 17,
 'dense': 18,
 'sparse': 19,
 'rag': 20,
 'is': 21,
 'documents': 22,
 'this': 23,
 'use': 24,
 'into': 25,
 'are': 26,
 'methods': 27,
 'as': 28,
 'generation': 29,
 'that': 30,
 'model': 31,
 'user': 32,
 'using': 33,
 'from': 34,
 'for': 35,
 'augmentation': 36,
 'on': 37,
 'vector': 38,
 'output': 39,
 'retrieved': 40,
 'models': 41,
 'interactions': 42,
 'large': 43,
 'queries': 44,
 'augment': 45,
 'specific': 46,
 'an': 47,
 'process': 48,
 'made': 49,
 'first': 50,
 'all': 51,
 'indexing': 52,
 'typically': 53,
 'embeddings': 54,
 'representations': 55,
 'text': 56,
 'structured': 57,
 'these': 58,
 'document': 59,
 'prompt': 60,
 'relevant': 61,
 'incorporate': 62,
 'such': 63,
 'encode': 64,
 'contain': 65,
 'zeros': 66,
 'improved': 67,
 'faster': 68,
 'dot': 69,
 'pr

In [7]:
input_seq = []
for sent in doc.split('\n'):
    tokenized_sent = tokenizer.texts_to_sequences([sent])[0]
    for i in range(1, len(tokenized_sent)):
        input_seq.append(tokenized_sent[:i+1])

In [8]:
input_seq[:15]

[[12, 72],
 [12, 72, 29],
 [12, 72, 29, 20],
 [12, 72, 29, 20, 21],
 [12, 72, 29, 20, 21, 5],
 [12, 72, 29, 20, 21, 5, 73],
 [12, 72, 29, 20, 21, 5, 73, 30],
 [12, 72, 29, 20, 21, 5, 73, 30, 74],
 [12, 72, 29, 20, 21, 5, 73, 30, 74, 75],
 [12, 72, 29, 20, 21, 5, 73, 30, 74, 75, 76],
 [12, 72, 29, 20, 21, 5, 73, 30, 74, 75, 76, 77],
 [12, 72, 29, 20, 21, 5, 73, 30, 74, 75, 76, 77, 41],
 [8, 12],
 [8, 12, 78],
 [8, 12, 78, 79]]

### Zero padding

In [9]:
max_len = max([len(i) for i in input_seq])
max_len

24

In [10]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_seq = pad_sequences(input_seq, maxlen = max_len, padding = 'pre')
padded_input_seq

array([[  0,   0,   0, ...,   0,  12,  72],
       [  0,   0,   0, ...,  12,  72,  29],
       [  0,   0,   0, ...,  72,  29,  20],
       ...,
       [  0,   0,   0, ...,   9,  18,  71],
       [  0,   0,   0, ...,  18,  71, 232],
       [  0,   0,   0, ...,  71, 232, 233]], dtype=int32)

### Create data for supervised learning

In [11]:
X = padded_input_seq[:, :-1]
y = padded_input_seq[:, -1]

In [12]:
X.shape, X

((419, 23),
 array([[  0,   0,   0, ...,   0,   0,  12],
        [  0,   0,   0, ...,   0,  12,  72],
        [  0,   0,   0, ...,  12,  72,  29],
        ...,
        [  0,   0,   0, ..., 231,   9,  18],
        [  0,   0,   0, ...,   9,  18,  71],
        [  0,   0,   0, ...,  18,  71, 232]], dtype=int32))

In [13]:
y.shape, y

((419,),
 array([ 72,  29,  20,  21,   5,  73,  30,  74,  75,  76,  77,  41,  12,
         78,  79,  80,  42,   9,   5,  43,  81,  31,  10,  82,  30,   1,
         31,   2,  32,  44,   9,  84,   2,   5,  85,  86,   3,  22,  33,
         23,   8,   2,  45,   8,  34,  88,  89,  90,  91,  92,  13,  23,
         93,  94,   2,  24,  95,  46,   4,  14,  96,   8,  97,  98,  99,
        100, 101,   2, 102, 103,  13,  14, 104, 105,   8, 106,  34,  47,
        107, 108,  20,  48,  21,  49, 109,   3, 110, 111, 112,  50,  51,
          1,  13, 113,   6, 114,   4, 115,  35,  24, 116,   1,  10, 118,
         15, 119,   3,   5,  12,  36,   4,  29, 120,   1,  13,   2,   6,
        121,  21, 122,  25,  10,  54, 123,  55,  16,   1, 124,   3,  43,
         11,   7,   6,  17,  37, 125, 126,  56, 127,  57,  14,  57,  13,
         35, 128, 129, 130,  54,  26, 131, 132,  16,   5,  38, 133,   2,
        134,  35,  59,  12,   3,  20,  48, 136, 137,  22,   4,  32, 138,
         25,  47,  10,  60,   2, 139, 140,

In [14]:
from tensorflow.keras.utils import to_categorical

y = to_categorical(y, num_classes = len(tokenizer.word_index)+1)
y.shape

(419, 234)

In [15]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

### LSTM Model

In [16]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, LSTM

In [17]:
model = Sequential()

model.add(Embedding(234, 100, input_length = 23))
model.add(LSTM(150))
model.add(Dense(234, activation = 'softmax'))
model.build(input_shape=(None, 23))

/opt/conda/lib/python3.10/site-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [18]:
model.compile(loss = 'categorical_crossentropy', optimizer = 'Adam', metrics = ['accuracy'])

In [19]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 23, 100)        │        23,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 150)            │       150,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 234)            │        35,334 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 209,334 (817.71 KB)

 Trainable params: 209,334 (817.71 KB)

 Non-trainable params: 0 (0.00 B)

In [20]:
model.fit(X, y, epochs = 100)

Epoch 1/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 3s 26ms/step - accuracy: 0.0171 - loss: 5.4513
Epoch 2/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.0536 - loss: 5.2806
Epoch 3/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.0417 - loss: 5.0413
Epoch 4/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.0300 - loss: 5.0572
Epoch 5/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.0322 - loss: 5.0046
Epoch 6/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.0679 - loss: 4.9448
Epoch 7/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.0531 - loss: 4.9991
Epoch 8/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.0539 - loss: 4.9554
Epoch 9/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.0469 - loss: 4.9387
Epoch 10/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.0699 - loss: 4.7746
Epoch 11/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.0579 - loss: 4.7942
Epoch 12/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step

In [21]:
max_len

24

In [22]:
text = "retrieval"

# tokenize
token_text = tokenizer.texts_to_sequences([text])[0]
# pad
padded_text = pad_sequences([token_text], maxlen = max_len, padding = 'pre')
# predict
predicted_out = model.predict(padded_text)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 170ms/step


In [23]:
pos = np.argmax(predicted_out)
for word, index in tokenizer.word_index.items():
    if index == pos:
        print(word)

augmented


In [24]:
text = "retrieval"
for i in range(4):
    # tokenize
    token_text = tokenizer.texts_to_sequences([text])[0]
    # pad
    padded_text = pad_sequences([token_text], maxlen = max_len, padding = 'pre')
    # predict
    predicted_out = model.predict(padded_text)
    pos = np.argmax(predicted_out)
    for word, index in tokenizer.word_index.items():
        if index == pos:
            text = text + " " + word
            print(text)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
retrieval augmented
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
retrieval augmented generation
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
retrieval augmented generation rag
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
retrieval augmented generation rag is


In [25]:
text = "deep learning"
for i in range(10):
    # tokenize
    token_text = tokenizer.texts_to_sequences([text])[0]
    # pad
    padded_text = pad_sequences([token_text], maxlen = max_len, padding = 'pre')
    # predict
    predicted_out = model.predict(padded_text)
    pos = np.argmax(predicted_out)
    for word, index in tokenizer.word_index.items():
        if index == pos:
            text = text + " " + word
            print(text)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
deep learning can
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
deep learning can be
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
deep learning can be improved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
deep learning can be improved with
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
deep learning can be improved with late
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
deep learning can be improved with late interactions
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
deep learning can be improved with late interactions with
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
deep learning can be improved with late interactions with a
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
deep learning can be improved with late interactions with a large
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
deep learning can be improved with late interactions with a large language
